### PR TITLE
Repin nixpkgs to nixos-unstable by git rebase

### PR DESCRIPTION
**Pull request by balsoft**
```
git fetch origin && git fetch upstream
git checkout master && git checkout -B repin
git rebase upstream/nixos-unstable
```

Had to change the pyln-client commit because the structure of python-packages.nix changed.

### CODE REVIEW

**Review by zhenyavinogradov — APPROVED** [review]

**Comment by zhenyavinogradov** [comment]
We should probably test the repin in the infra repos before merging it here, to find and fix at least build-time problems, then yolo it to the servers.

**Comment by balsoft** [comment]
Aquarius-infra passes with this diff:

```
diff --git a/flake.lock b/flake.lock
index b3dafc2..4c07254 100644
--- a/flake.lock
+++ b/flake.lock
@@ -190,11 +190,11 @@
     },
     "nixpkgs_2": {
       "locked": {
-        "lastModified": 1601640588,
-        "narHash": "sha256-EKCgoeOA5i3DQQx2lfyzvjwCiklnSCXsnHzh9gg1AD4=",
+        "lastModified": 1608910604,
+        "narHash": "sha256-kjTAJGPmfckaZGnn9ouPY/v07GKc9vOFlBesyWiCENU=",
         "owner": "serokell",
         "repo": "nixpkgs",
-        "rev": "1e22f7603d223a67e7cd219939e1c1042419ff24",
+        "rev": "5f5469b38da431a56889b5a06597be6c4808b345",
         "type": "github"
       },
       "original": {
diff --git a/terraform/provider.tf b/terraform/provider.tf
index 313a7ff..2c5db84 100644
--- a/terraform/provider.tf
+++ b/terraform/provider.tf
@@ -1,5 +1,5 @@
 provider  "aws" {
-  version = "~> 2.15"
+  version = "~> 3.20"
   region = "eu-west-2"
 }

@@ -13,6 +13,6 @@ data "vault_generic_secret" "hcloud_token" {
 }

 provider "hcloud" {
-  version = "~> 1.16.0"
+  version = "~> 1.22.0"
   token = data.vault_generic_secret.hcloud_token.data["token"]
 }
```

**Comment by balsoft** [comment]
Pegasus-infra passes as is

**Comment by balsoft** [comment]
Tezos-infra fails:

```
cycle detected in the references of '/nix/store/jh0jv5rvv27613gmv01pb69c10mnjign-uecc-lib' from '/nix/store/ni6dkacvgsmfv9c2ls3d85yzz0pk0pzr-uecc'
```

Will have to be fixed in tezos-packaging probably

**Review by mkaito — APPROVED** [review]
If any infra repos require changes here, we can assess them in separate PRs.

**Comment by zhenyavinogradov** [comment]
Right, @balsoft I think if the -infra repos need changes you should make PRs for them so we can work on making them build together.

**Comment by balsoft** [comment]
Ok, force-pushing to master

**Pull request merged**
