### PR TITLE
[TM-568] danger-gitlab: init at 8.0.0

### PR DESCRIPTION
**Pull request by zhenyavinogradov**
`danger` automates some checks for PRs https://danger.systems/ruby/, and `danger-gitlab` is a wrapper gem which includes `gitlab` package to make it work for gitlab MRs. Morley devs want to try it: https://issues.serokell.io/issue/TM-568

### CODE REVIEW

**Comment by balsoft** [comment]
Any reason this doesn't target upstream?

**Comment by zhenyavinogradov** [comment]
Morley devs are not sure if they actually want to use it or not, they just want to check it out. If they end up using it, it would be good to make a PR upstream as well

**Comment by balsoft** [comment]
In that case, I suggest not merging this PR and just using the branch?

**Comment by zhenyavinogradov** [comment]
It will be problematic if we to make another update to this repo and use it in morley, e.g. rebase it against upstream nixpkgs, or just make some small change that we need in other repos as well. Because then we'll need to make update to this branch separately.

**Comment by balsoft** [comment]
Ok, I see. Well, let's hope it won't take too long to evaluate whether we want it or not.

**Review by balsoft — APPROVED** [review]

**Pull request merged**
