### PR TITLE
[OPS-1269] Rebase against upstream 09.2021

### PR DESCRIPTION
**Pull request by zhenyavinogradov**
Diff from upstream before repin: https://github.com/NixOS/nixpkgs/compare/nixos-unstable-small...serokell:3b10c4c8191ba684a45ca4e46a9281d4e26b7f76
Diff from uptsream after repin: https://github.com/NixOS/nixpkgs/compare/nixos-unstable-small...serokell:zhenya/ops1269-rebase-2021-09

So the only change is that we can drop danger-gitlab commits because they were merged upstream.

### CODE REVIEW

**Comment by zhenyavinogradov** [comment]
`stdenv` in nixpkgs has been refactored recently, and it causes a major regression for haskell.nix projects: https://github.com/NixOS/nixpkgs/issues/136903. I don't know the best way to work around it yet, so I think it would be good to update to a less recent nixpkgs revision this time (https://github.com/NixOS/nixpkgs/commit/7c38b03f742a657bf38e9579adeb608fc7cc5f1a), until upstream suggests a fix.

**Comment by notgne2** [comment]
@zhenyavinogradov nixpkgs tends to be slow upstream but haskell.nix a little less so, would `overrideDerivation` be a reasonable workaround? otherwise maybe we can have the conditional outside of the override so it's never called on non-Windows at least

**Comment by zhenyavinogradov** [comment]
> `overrideDerivation`

I checked it like this, but it fails with `error: attribute 'override' missing`:

```nix
let nixpkgs-src = builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/b799f604381ac04d88b62ed33eb764fde5a83483.tar.gz";
in {
  gcc-overlay = (import nixpkgs-src {
    overlays = [(final: prev: {
      libmpc = prev.lib.overrideDerivation prev.libmpc (drv: {});
    })];
  }).gcc;
}
```

> have the conditional outside of the override

haskell.nix says that the condition has to be at the package level, otherwise there'll be some issues, I'm not sure which exactly: https://github.com/input-output-hk/haskell.nix/blob/a7264994ed92858e8dd7c586786a3c51599ba48a/overlays/windows.nix#L1

Another idea I had is to disable the windows overlay in the projects where we don't need windows builds, but it will be a pain to do this in each project, and to roll it back when the issue is fixed.

**Comment by zhenyavinogradov** [comment]
What about merging this PR, while we are coming up with a solution? I don't want us to stall on this. When haskell.nix or nixpkgs decide on a fix, we'll just rebase again.

**Comment by zhenyavinogradov** [comment]
I found that edna fails to build unless we update poetry2nix, I cherry-picked the update here

**Review by notgne2 — APPROVED** [review]

**Pull request merged**
