### PR TITLE
Repin nixpkgs

### PR DESCRIPTION
**Pull request by mkaito**
Does not include https://github.com/NixOS/nixpkgs/commit/0b0afcae166bb82a40eda3a95dc22239f7e68601 because that probably breaks our gitlab-runner config completely.

### CODE REVIEW

**Comment by zhenyavinogradov** [comment]
I think it's hard to evaluate this when it's just merged into our fork. Maybe we should take current HEAD from upstream and reapply our custom commits?

**Comment by kirelagin** [comment]
^ Yes.

What we should do is maintain a branch-per-feature/fix we make, and then just rebase them each time onto new master. Unfortunately, I have this workflow only in my head and never wrote it down, and it also needs an automation tool that will “unmerge” changes from our current master until merge-base to figure out the set of branches that need to be rebased, and then will rebase them onto the new upstream master.

**Comment by mkaito** [comment]
While I appreciate perfect-world solution ideas, we kinda need the repin to happen. You're not supposed to review the attached 300k line diff, that's nonsense.

You're supposed to use this branch in `profiles` and `-infra` repos, and rebuild to see what breaks. The two problems I encountered on Jupiter, I made YT issues and posted in #sre-it-ops about.

Yeah, I wish this could be automated.

**Comment by zhenyavinogradov** [comment]
Can we use `git rebase` for this? I think it's not hard, I tried it here: https://github.com/serokell/nixpkgs/pull/34, it looks like we only have 6 commits which are don't have an equivalent in uptsream. Tell me what you think

**Comment by mkaito** [comment]
Looks way cleaner than this.

**Pull request closed without merging**
