### PR TITLE
[26-01-23] Repin

### PR DESCRIPTION
**Pull request by PhilTaken**
Next repin coming up!

### CODE REVIEW

**Review by rvem — APPROVED** [review]
LGTM.

We usually force-push repin branch directly to `master`. Also, we should preserve the current master revision in the git history to avoid getting 404 in future

**Comment by rvem** [comment]
We can update repos like `serokell.nix` manually and let `update-daemon` do the update for all infra repos

**Comment by PhilTaken** [comment]
> We usually force-push repin branch directly to `master`. Also, we should preserve the current master revision in the git history to avoid getting 404 in future

the best way to do that might be to squash the merge I think. rebase would rewrite history

**Comment by rvem** [comment]
Is there anything that stops us from applying this repin in this repo and propagating it to our infra?

**Pull request merged**
